"""
Mall Customers Segmentation.ipynb

Automatically generated by Colab.

Original dataset:
Mall_Customers.csv
"""

"""
💡 Project Overview

Customer Segmentation using K-Means Clustering

Objective:
- Segment mall customers into different groups based on their Annual Income 
  and Spending Score.

Dataset:
- Features Used:
    1. Annual Income (k$)
    2. Spending Score (1–100)

Algorithm Used:
- K-Means Clustering (Unsupervised Learning)

Goal:
- Identify distinct customer groups to help businesses improve marketing strategies.
"""

# ===============================
# 1️⃣ Import Required Libraries
# ===============================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.cluster import KMeans

# ===============================
# 2️⃣ Load Dataset
# ===============================

customer_data = pd.read_csv('/content/Mall_Customers.csv')

print("First 5 rows:")
print(customer_data.head())

# ===============================
# 3️⃣ Exploratory Data Analysis
# ===============================

print("\nDataset Shape:", customer_data.shape)

print("\nDataset Info:")
customer_data.info()

print("\nMissing Values:\n", customer_data.isnull().sum())

print("\nStatistical Summary:\n", customer_data.describe())

# ===============================
# 4️⃣ Feature Selection
# ===============================

# Selecting Annual Income and Spending Score
X = customer_data.iloc[:, [3, 4]].values

print("\nSelected Features (First 5 rows):")
print(X[:5])

# =====================================================
# 5️⃣ Finding Optimal Number of Clusters (Elbow Method)
# =====================================================

"""
WCSS (Within-Cluster Sum of Squares):
Measures how compact the clusters are.
Lower WCSS = better clustering.
"""

wcss = []

for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, init='k-means++', random_state=42)
    kmeans.fit(X)
    wcss.append(kmeans.inertia_)

# Plot Elbow Graph
sns.set()
plt.figure(figsize=(6,4))
plt.plot(range(1, 11), wcss, marker='o')
plt.title('Elbow Method for Optimal Clusters')
plt.xlabel('Number of Clusters')
plt.ylabel('WCSS')
plt.show()

print("Optimal number of clusters appears to be: 5")

# ===============================
# 6️⃣ Train K-Means Model
# ===============================

kmeans = KMeans(n_clusters=5, init='k-means++', random_state=42)

# Predict cluster labels
Y = kmeans.fit_predict(X)

print("\nCluster Labels (First 20 customers):")
print(Y[:20])

# ===============================
# 7️⃣ Visualizing Customer Clusters
# ===============================

plt.figure(figsize=(8, 6))

# Plot each cluster
plt.scatter(X[Y == 0, 0], X[Y == 0, 1], s=50, label='Cluster 1')
plt.scatter(X[Y == 1, 0], X[Y == 1, 1], s=50, label='Cluster 2')
plt.scatter(X[Y == 2, 0], X[Y == 2, 1], s=50, label='Cluster 3')
plt.scatter(X[Y == 3, 0], X[Y == 3, 1], s=50, label='Cluster 4')
plt.scatter(X[Y == 4, 0], X[Y == 4, 1], s=50, label='Cluster 5')

# Plot Centroids
plt.scatter(
    kmeans.cluster_centers_[:, 0],
    kmeans.cluster_centers_[:, 1],
    s=200,
    c='black',
    marker='X',
    label='Centroids'
)

plt.title('Customer Segmentation using K-Means')
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score (1-100)')
plt.legend()
plt.show()

# ===============================
# 8️⃣ Business Interpretation
# ===============================

"""
Possible Customer Groups Interpretation:

Cluster 1 → High Income, High Spending  (Premium Customers 💎)
Cluster 2 → Low Income, High Spending   (Impulse Buyers 🛍️)
Cluster 3 → High Income, Low Spending   (Careful Investors 💼)
Cluster 4 → Low Income, Low Spending    (Budget Customers 💰)
Cluster 5 → Average Income & Spending   (Regular Customers 👥)

These insights can help businesses:
- Create targeted marketing campaigns
- Offer personalized discounts
- Improve customer retention strategies
"""